<?php
$subject = array(


	'civil' => array(
		'1' => array(
			'BASIC MATHEMATICS',
			'ENGLISH',
			'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
			'ENGINEERING PHYSICS (GROUP-1)',
			'BASIC ENGINEERING DRAWING',
			'COMPUTER APPLICATION & GRAPHICS'
		),
		'2' => array(
			'CONTRIBUTOR PERSONALITY DEVELOPMENT',
			'ADVANCED MATHEMATICS (GROUP-2)',
			'APPLIED MECHANICS',
			'APPLIED CHEMISTRY (GROUP-1)',
			'BUILDING DRAWING',
			'BASIC MECHANICAL ENGINEERING',
			'CIVIL ENGINEERING WORKSHOP PRACTICE'
		),
		'3' => array(
			'BUILDING MATERIALS',
			'CONSTRUCTION TECHNOLOGY',
			'HYDRAULICS',
			'STRUCTURAL MECHANICS',
			'SURVEYING'
		),
		'4' => array(
			'STRUCTURAL MECHANICS-II',
			'ADVANCED SURVEYING',
			'BASIC TRANSPORTATION ENGINEERING',
			'WATER RESOURCES MANAGEMENT',
			'SOIL MECHANICS',
			'COMPUTER AIDED DRAWING'
		),
		'5' => array(
			'DESIGN OF STEEL STRUCTURE',
			'CONCRETE TECHNOLOGY',
			'WATER SUPPLY & SANITARY ENGGINEERING',
			'ESTIMATING , COSTING & VALUATION',
			'ADVANCE CONSTRUCTION TECHNOLOGY',
			'HIGHWAY ENGINEERING',
			'IRRIGATION ENGINEERING',
			'ENVIRONMENTAL ENGINEERING &POLLUTION CONTROL',
			'PROJECT-I'
		),
		'6' => array(
			'DESIGN OF REINFORCED CONCRETE STRUCTURES',
			'CONSTRUCTION QUALITY CONTROL & MONITORING',
			'CONSTRUCTION PROJECT MANAGEMNET',
			'BUILDING SERVICES',
			'MAINTANANCE & REHABILATION OF STRUCTURES',
			'RAILWAY , HARBOUR & TUNNEL ENGINEERING',
			'TRAFFIC ENGINEERING',
			'PAVEMENT DESIGN',
			'GROUND WATER ENGINEERING',
			'ADVANCE HYDROLOGY',
			'SOLID WASTE MANAGEMENT',
			'WATER AND WASTE WATER MANAGEMENT',
			'PROJECT-II'
		),
	),

	'computer' => array(
		'1' => array(
			'ENGINEERING MATHEMATICS-I',
			'ELEMENTS AND DEVICES OF COMPUTING TECHNOLOGY PHYSICS',
			'COMPUTER PROGRAMMING',
			'COMMUNICATIVE ENGLISH',
			'WORKSHOP TECHNOLOGY',
			'ENGINEERING DRAWING'
		),
		'2' => array(
			'ENGINEERING MATH-II',
			'CHEMISTRY',
			'APPLIED MECHANICS',
			'ELECTRICAL  ENGINEERING',
			'OBJECT ORIENTED PROGRAMMING',
			'DIGITAL LOGIC'
		),
		'3' => array(
			'ENGINEERING MATH-III',
			'INFORMATION SYSTEM DESIGN',
			'ELECTRONIC DEVICES & CIRCUIT',
			'DATA STRUCTURE AND ALGORITHM',
			'COMPUTER ORGANIZATION AND DESIGN',
			'PROJECT'
		),
		'4' => array(
			'MICROPROCESSOR',
			'DATABASE MANAGEMENT SYSTEM',
			'FREE AND OPEN SOURCE PROGRAMS',
			'DISCRETE MATHEMATICS',
			'COMMUNICATION SYSTEM',
			'APPLIED SOCIOLOGY'
		),
		'5' => array(
			'NUMERICAL METHOD',
			'ALGORITHM ANALYSIS AND DESIGN',
			'COMPUTER GRAPHICS',
			'OPERATING SYSTEM',
			'RESEARCH METHODOLOGY',
			'PROJECT'
		),
		'6' => array(
			'PROJECT AND ORGANIZATION MANAGEMENT',
			'THEORY OF COMPUTATION',
			'MULTIMEDIA TECHNOLOGY',
			'COMPUTER NETWORK',
			'PROBABILITY AND STATISTICS',
			'ENGINEERING ECONOMICS'
		),
		'7' => array(
			'ENTREPRENEURSHIP',
			'ARTIFICIAL INTELLIGENCE',
			'SOFTWARE ENGINEERING',
			'SIMULATION AND MODELING',
			'ELECTIVE-I',
			'PROJECT'
		),
		'8' => array(
			'DATA MINING AND DATA WAREHOUSING',
			'ENGINEERING PROFESSIONAL PRACTICE',
			'CRYPTOGRAPHY',
			'ADVANCE COMPUTER ARCHITECTURE',
			'ELECTIVE II',
			'PROJECT'
		),
	),

	'ec' => array(
		'1' => array(
			'BASIC MATHEMATICS',
			'ENGLISH',
			'BASIC PHYSICS(GROUP-2)',
			'ELECTRONIC COMPONENTS & PRACTICE',
			'BASIC OF ELECTRICAL ENGINEERING',
			'BASIC OF COMPUTER & INFORMATION TECHNOLOGY'
		),
		'2' => array(
			'CONTRIBUTOR PERSONALITY DEVELOPMENET',
			'ADVANCED MATHEMATICS (GROUP-1)',
			'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
			'ELECTRONIC CIRCUITS & APPLICATIONS',
			'ELECTRONIC NETWORKS',
			'ELECTRONICS WORKSHOP'
		),
		'3' => array(
			'ANTENNA & WAVE PROPAGATION',
			'ANALOG ELECTRONICS',
			'PRINCIPLE OF ELECTRONIC COMMUNICATION',
			'DIGITAL LOGIC DESIGN',
			'PROGRAMMING IN C'
		),
		'4' => array(
			'MICROPROCESSOR AND ASSEMBLY LANGUAGE PROGRAMMING',
			'DIGITAL COMMUNICATION',
			'OPTICAL COMMUNICATION',
			'ELECTRONICS INSTRUMENTS AND MEASUREMENT',
			'INDUSTRIAL ELECTRONICS',
			'CIRCUIT DESIGN TOOLS'
		),
		'5' => array(
			'MICROCONTROLLER',
			'MOBILE COMMUNICATION',
			'MICROWAVE & RADAR ENGINEERING',
			'SOFTWARE PRACTICES',
			'COMPUTER NETWORKS',
			'INSTRUMENTATION & CONTROL ENGG',
			'PROJECT-I'
		),
		'6' => array(
			'ENTERPRENURSHIP AND INDUSTRIAL MANAGEMENT',
			'CONSUMER ELECTRONICS',
			'MAINTENANCE OF ELECTRONICS EQUIPMENTS',
			'VLSI',
			'EMBEDED SYSTEM',
			'MULTIMEDIA COMMUNICATION',
			'INDUSTRIAL AUTOMATION',
			'ROBOTICS & AUTOTRONICS',
			'PROJECT - II'
		),
	),

	'architecture' => array(
		'1' => array(
			'BASIC MATHEMATICS',
			'ENGLISH',
			'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
			'COMPUTER PROGRAMMING',
			'FUNDAMENTAL OF DIGITAL ELECTRONIC',
			'FUNDAMENTAL OF COMPUTER APPLICATION'
		),
		'2' => array(
			'CONTRIBUTOR PERSONALITY DEVELOPMENET',
			'ADVANCED MATHEMATICS(GROUP-1)',
			'BASIC PHYSICS (GROUP-2)',
			'BASIC ELECTRONICS',
			'ADVANCED COMPUTER PROGRAMMING',
			'FUNDAMENTAL OF INFORMATION TECHNOLGY'
		),
		'3' => array(
			'DIGITAL MEMORY SYSTEM',
			'OPERATING SYSTEM',
			'COMPUTER GRAPHICS',
			'DATA STRUCTURE',
			'SOFTWARE PRACTICES WITH VB.NET'
		),
		'4' => array(
			'INFORMATION COMMUNICATION TECHNOLOGY',
			'OBJECT ORINTED PROGRAMMING',
			'FUNDAMENTALS OF SOFTWARE DEVELOPMENT',
			'INTERNET TECHNOLOGY',
			'DATABASE MANAGEMENT'
		),
		'5' => array(
			'JAVA PROGRAMMING',
			'INFORMATION COMMUNICATION NETWORKS',
			'ESSENTIALS OF NETWORK SECURITY',
			'WEB PROGRAMMING USING ASP.NET',
			'MANAGEMENT INFORMATION SYSTEM',
			'PROJECT - I'
		),
		'6' => array(
			'WEB AND NETWORK SECURITY',
			'ADVANCE JAVA PROGRAMMING',
			'ANDROID APPS DEVELOPMENT',
			'WEB DESIGNING USING PHP AND MYSQL',
			'DATA MINING AND WAREHOUSING',
			'DATABASE ADMINISTRATION',
			'PROJECT-II'
		),
		'7' => array(
			'WEB AND NETWORK SECURITY',
			'ADVANCE JAVA PROGRAMMING',
			'ANDROID APPS DEVELOPMENT',
			'WEB DESIGNING USING PHP AND MYSQL',
			'DATA MINING AND WAREHOUSING',
			'DATABASE ADMINISTRATION',
			'PROJECT-II'
		),
		'8' => array(
			'WEB AND NETWORK SECURITY',
			'ADVANCE JAVA PROGRAMMING',
			'ANDROID APPS DEVELOPMENT',
			'WEB DESIGNING USING PHP AND MYSQL',
			'DATA MINING AND WAREHOUSING',
			'DATABASE ADMINISTRATION',
			'PROJECT-II'
		),
		'9' => array(
			'WEB AND NETWORK SECURITY',
			'ADVANCE JAVA PROGRAMMING',
			'ANDROID APPS DEVELOPMENT',
			'WEB DESIGNING USING PHP AND MYSQL',
			'DATA MINING AND WAREHOUSING',
			'DATABASE ADMINISTRATION',
			'PROJECT-II'
		),
		'10' => array(
			'WEB AND NETWORK SECURITY',
			'ADVANCE JAVA PROGRAMMING',
			'ANDROID APPS DEVELOPMENT',
			'WEB DESIGNING USING PHP AND MYSQL',
			'DATA MINING AND WAREHOUSING',
			'DATABASE ADMINISTRATION',
			'PROJECT-II'
		),
	),

);
